#! /bin/sh

sxhkd &

. "${HOME}/.cache/wal/colors.sh"

bspc monitor -d general fun term. media misc.

bspc config border_width         1
bspc config window_gap          38

bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config focus_follows_pointer true

bspc config normal_border_color "$color3"
bspc config active_border_color "$color3"
bspc config focused_border_color "$color3"
bspc config presel_feedback_color "$color3"

xrdb merge $HOME/.Xresources

sh $HOME/.screenlayout/screen.sh

feh --bg-fill $HOME/.rsrc/wall.png

sh $HOME/.config/polybar/autostart.sh

picom 

